version: '3'

services:
  php:
    build: ./docker/php
    volumes:
        - ./:/usr/helloprint/
    working_dir: /usr/helloprint/

  postgres:
    build: ./docker/postgres
    restart: always
    environment:
      POSTGRES_USER: hellouser
      POSTGRES_PASSWORD: hellopass
      POSTGRES_DB: helloprint
      
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - 2181:2181

  kafka:
    image: wurstmeister/kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENERS: INSIDE://:9092,OUTSIDE://:9094
      KAFKA_ADVERTISED_LISTENERS: INSIDE://:9092,OUTSIDE://kafka:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_CREATE_TOPICS: "TopicA:1:1,TopicB:1:1,Requester:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE

  connect:
    image: debezium/connect
    ports:
      - 8083:8083
    environment:
      GROUP_ID: 1
      BOOTSTRAP_SERVERS: kafka:9092
      CONFIG_STORAGE_TOPIC: "postgres-config"
      OFFSET_STORAGE_TOPIC: "postgres-offset"
    links:
      - "zookeeper:zookeeper"
      - "postgres:postgres"
      - "kafka:kafka"